"""
The command line module provides the main function of the application.
"""
import sys
import json
import os
import click
from smelly_python.code_smell import CodeSmell
from .generator.webpage_generator import generate_webpage


@click.command()
@click.option('--file', help='Specify the json file generated by pylint.')
@click.option('--command', help='The command to run pylint')
def main(file, command):
    """
    Main command line interface.
    Takes the first command line argument to be the json generated by pylint.
    """
    if ((file is not None) and (command is not None) or (file == command)):
        print("Please only provide either --file or --command argument")
        sys.exit(1)
    file_name = file
    if command:
        print('Running pylint...')
        print(command + ' --output-format=json > output.json')
        os.system(command + ' --output-format=json > output.json')
        file_name = './output.json'

    with open(file_name, 'r', encoding='utf-8') as input_file:
        dict_data = json.load(input_file)
        code_smells = CodeSmell.convert_dict(dict_data)
        print(code_smells)
        generate_webpage(code_smells)
